# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: R
sudo: false
cache: packages

r_github_packages:
  - ThinkR-open/attachment  # pre-install to avoid vignette package errors

# build matrix; turn on vdiffr only on r release
matrix:
  include:
  - r: devel
  - r: release
    env: VDIFFR_RUN_TESTS=true
    before_cache:
    - Rscript -e 'remotes::install_cran("pkgdown")'
    - Rscript -e 'remotes::install_github("ThinkR-open/thinkrtemplate")'
    deploy:
      provider: pages
      skip-cleanup: true
      github-token: $GITHUB_PAT
      keep-history: true
      local-dir: docs
      on:
        branch: master
      skip_cleanup: true
  - r: oldrel
  - r: 3.2

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'pkgdown::build_site()'

