path.n: NAMESPACE
path.d: DESCRIPTION
dir.r: R
dir.v: vignettes
dir.t: tests
extra.suggests:
  - testthat
  - rstudioapi
  - renv
  - lifecycle
pkg_ignore:
  - remotes
  - i
  - usethis
  - rstudioapi
  - renv
  - gitlab
  - git
  - local
  - find.rscript
  - bioc
  - find.me
  - findme1
  - findme2
  - findme3
  - findme4
  - findme5
  - findme6
  - findme1a
  - findme2a
  - findme3a
  - findme4a
  - findme5a
  - findme6a
  - ggplot3
  - svn
  - pkgload
document: yes
normalize: no
inside_rmd: no
must.exist: yes
check_if_suggests_is_installed: yes
