path: '.'
path.n: NAMESPACE
path.d: DESCRIPTION
dir.r: R
dir.v: vignettes
dir.t: ''
extra.suggests:
- testthat
- rstudioapi
- renv
- lifecycle
pkg_ignore:
- remotes
- i
- usethis
- rstudioapi
- renv
- gitlab
- git
- local
- find.rscript
- bioc
document: yes
normalize: no
inside_rmd: no
must.exist: yes
check_if_suggests_is_installed: yes
