path.n: NAMESPACE
path.d: DESCRIPTION
dir.r: R
dir.v: vignettes
dir.t: tests
extra.suggests:
- testthat
- rstudioapi
- renv
- lifecycle
pkg_ignore:
- bioc
- bookdown
- dont.find.me3
- dont.find.me4
- dplyr
- fakepkg
- find.me
- find.me5.from.keep
- find.rscript
- findedge0
- findedge1
- findedge10
- findedge11
- findedge12
- findedge2
- findedge3
- findedge4
- findedge5
- findedge6
- findedge7
- findedge8
- findedge9
- findme1
- findme1a
- findme2
- findme2a
- findme3
- findme3a
- findme4
- findme4a
- findme5
- findme5a
- findme6
- findme6a
- ggplot3
- git
- gitlab
- i
- local
- pkgfake
- pkgload
- remotes
- renv
- rstudioapi
- svn
- usethis
document: yes
normalize: no
inside_rmd: no
must.exist: yes
check_if_suggests_is_installed: yes
