flat_create_dependencies_file.Rmd:
  path: dev/flat_create_dependencies_file.Rmd
  state: active
  R:
  - R/create_dependencies_file.R
  - R/dependencies_file_text.R
  tests:
  - tests/testthat/test-dependencies_file_text.R
  - tests/testthat/test-create_dependencies_file.R
  vignettes: vignettes/create-dependencies-file.Rmd
flat_save_att_params.Rmd:
  path: dev/flat_save_att_params.Rmd
  state: active
  R:
  - R/load_att_params.R
  - R/save_att_params.R
  tests:
  - tests/testthat/test-save_att_params.R
  - tests/testthat/test-load_att_params.R
  vignettes: vignettes/save-attachment-config.Rmd
