# WARNING - Generated by {fusen} from dev/flat_save_att_params.Rmd: do not edit by hand

#' load_att_params
#' 
#' @param path_to_yaml character The path to the yaml file
#' 
#' @importFrom yaml read_yaml
#' @importFrom glue glue
#' 
#' @return list A named list of att_amend_desc parameters
#' 
#' @export
#' @examples
#' # create a list of parameters and tmp file name
#' parameter_list <- list(
#'   pkg_ignore = c("remotes", "i"),
#'   extra.suggests = c("testthat", "rstudioapi")
#' )
#' yaml_path <- paste0(tempfile(pattern = "save_att"), ".yaml")
#' 
#' # save params
#' save_att_params(param_list = parameter_list,
#'                 path_to_yaml = yaml_path)
#' 
#' # read yaml file
#' config_params <- load_att_params(path_to_yaml = yaml_path)
#' 
#' # clear created yaml file
#' unlink(yaml_path)
#' 
load_att_params <- function(
    path_to_yaml = "config_attachment.yaml"
    ){
    
  # check yaml file exist
  if (isFALSE(file.exists(path_to_yaml))){
    stop(glue("The att_amend_desc() config file {path_to_yaml} does not exist"))
  }
  
  # read yaml
  param_list <- read_yaml(file = path_to_yaml)
  
  # Check each name in list corresponds to a parameter name
  att_param_names <- names(formals(att_amend_desc))
  input_names <- names(param_list)
  all_inputs_are_params <- all(input_names %in% att_param_names)
  if (isFALSE(all_inputs_are_params)){
    bad_names <- input_names[!input_names %in% att_param_names]
    stop(paste0("Unexpected parameters in config : ", paste0(bad_names, collapse = " ; ")))
  }
  
  # Show parameters used from config
  message("att_amend_desc() parameter loaded are : \n",
          paste0(
            glue("{names(param_list)} = {param_list}"),
            collapse = "\n"
            )
          )
  
  # return parameters
  return(param_list)
  
}
