# WARNING - Generated by {fusen} from dev/flat_save_att_params.Rmd: do not edit by hand

#' save_att_params
#'
#' @param param_list list A named list of all parameters to save
#' @param path_to_yaml character The path to the yaml file
#' @param overwrite logical Whether to overwrite the yaml file if it already exists
#' 
#' @importFrom yaml write_yaml
#' 
#' @return character The path to the yaml file
#' @export
#' @examples
#' # create a list of parameters and tmp file name
#' parameter_list <- list(
#'   pkg_ignore = c("remotes", "i"),
#'   extra.suggests = c("testthat", "rstudioapi")
#' )
#' yaml_path <- paste0(tempfile(pattern = "save_att"), ".yaml")
#' 
#' # save params
#' save_att_params(param_list = parameter_list,
#'                 path_to_yaml = yaml_path)
#' 
#' # clear created yaml file
#' unlink(yaml_path)
save_att_params <- function(
    param_list,
    path_to_yaml = "config_attachment.yaml",
    overwrite = FALSE
    ) {
  
  # Check each name in list corresponds to a parameter name
  att_param_names <- names(formals(att_amend_desc))
  input_names <- names(param_list)
  all_inputs_are_params <- all(input_names %in% att_param_names)
  if (isFALSE(all_inputs_are_params)){
    bad_names <- input_names[!input_names %in% att_param_names]
    stop(paste0("Unexpected parameters to save : ", paste0(bad_names, collapse = " ; ")))
  }
  
  # Write params to yaml
  yaml_exists <- file.exists(path_to_yaml)
  
  if (isTRUE(yaml_exists & !overwrite)) {
    stop("yaml file already exists and overwriting is not permitted")
  } else {
    write_yaml(
      x = param_list,
      file = path_to_yaml
    )
    message("Saving attachment parameters to yaml config file")
  }

  return(path_to_yaml)
}
